# Generated by Django 3.0.10 on 2020-10-07 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermodel',
            name='profile_pic',
        ),
    ]
