# Generated by Django 3.0.10 on 2020-10-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201007_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='profile_pic',
            field=models.ImageField(blank=True, default='blank.png', null=True, upload_to=''),
        ),
    ]
